import {
  SHOW_AUTH_LOADING,
  HIDE_AUTH_LOADING,
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILED,
  VERIFY_EMAIL_SUCCESS,
  VERIFY_EMAIL_FAILED,
  REQUEST_PHONE_CODE_FAILED,
  VALIDATE_PHONE_CODE_SUCCESS,
  VALIDATE_PHONE_CODE_FAILED,
  HIDE_ALERT,
  SAVE_USER,
  AUTH_SET_NAME,
  AUTH_SET_CITY,
  AUTH_SET_EMAIL,
  AUTH_SET_STATE,
  SIGN_UP_SUCCESS,
  SIGN_UP_FAILED,
  FORGOT_PASSWORD_SUCCESS,
  FORGOT_PASSWORD_FAILED,
} from '../../types/authenticationTypes'
import { AUTH_INITIAL_STATE } from './constants'
import {
  showLoading,
  hideLoading,
  signInSuccess,
  signInFailed,
  verifyEmailSuccess,
  verifyEmailFailed,
  requestPhoneCodeFailed,
  validatePhoneCodeSuccess,
  validatePhoneCodeFailed,
  hideAlert,
  saveUser,
  setName,
  setEmail,
  setCity,
  setState,
  signUpSuccess,
  signUpFailed,
  forgotPasswordSuccess,
  forgotPasswordFailed,
} from './handlers'

export const actionHandlers = {
  [SHOW_AUTH_LOADING]: showLoading,
  [HIDE_AUTH_LOADING]: hideLoading,
  [SIGN_IN_SUCCESS]: signInSuccess,
  [SIGN_IN_FAILED]: signInFailed,
  [VERIFY_EMAIL_SUCCESS]: verifyEmailSuccess,
  [VERIFY_EMAIL_FAILED]: verifyEmailFailed,
  [REQUEST_PHONE_CODE_FAILED]: requestPhoneCodeFailed,
  [VALIDATE_PHONE_CODE_SUCCESS]: validatePhoneCodeSuccess,
  [VALIDATE_PHONE_CODE_FAILED]: validatePhoneCodeFailed,
  [HIDE_ALERT]: hideAlert,
  [SAVE_USER]: saveUser,
  [AUTH_SET_NAME]: setName,
  [AUTH_SET_CITY]: setCity,
  [AUTH_SET_STATE]: setState,
  [AUTH_SET_EMAIL]: setEmail,
  [SIGN_UP_SUCCESS]: signUpSuccess,
  [SIGN_UP_FAILED]: signUpFailed,
  [FORGOT_PASSWORD_SUCCESS]: forgotPasswordSuccess,
  [FORGOT_PASSWORD_FAILED]: forgotPasswordFailed,
}

export const authReducerConfig = {
  initialState: AUTH_INITIAL_STATE,
  actionHandlers
}
