import { FEED_INITIAL_STATE } from './constants'
import {
  LOADING_POST,
  PUBLISHING_POST,
  PUBLISH_POST_SUCCESS,
  LOADING_POSTS,
  FETCH_POSTS,
  REFRESH_POSTS,
  UPDATE_POST_STATUS_ON_FEED,
  SHOW_FEED_LOADING,
  HIDE_FEED_LOADING,
  LIKE_POST_SUCCESS,
  UNDO_LIKE_POST_SUCCESS,
  FETCH_COMMENTS,
  FETCH_MORE_COMMENTS,
  LOADING_COMMENTS,
  PUBLISH_COMMENT_SUCCESS,
  EDIT_COMMENT_SUCCESS,
  DELETE_COMMENT_SUCCESS,
  CLEAR_COMMENTS,
  SHARE_POST_SUCCESS,
  LIKE_COMMENT_SUCCESS,
  UNDO_LIKE_COMMENT_SUCCESS,
  SAVE_OPEN_GRAPH,
  SAVE_OG_URLS_FOUND,
  SAVE_OG_URLS_DISMISSED,
  LOADING_OG,
  CLEAR_NEW_POST_STATE,
  DELETE_POST_SUCCESS,
  VOTE_POST_SUCCESS,
  SET_USER_LOCATION,
} from '../../types/feedTypes'
import {
  loadingPost,
  publishingPost,
  publishPost,
  loadingPosts,
  fetchPosts,
  refreshPosts,
  saveOpenGraph,
  saveOgUrlsFound,
  saveOgUrlsDismissed,
  loadingOg,
  updatePostStatusOnFeed,
  showFeedLoadingHandler,
  hideLoadingHandler,
  likePost,
  undolikePost,
  fetchComments,
  fetchMoreComments,
  loadingComments,
  publishCommentSuccess,
  editCommentSuccess,
  deleteCommentSuccess,
  clearComments,
  sharePostSuccess,
  likeComment,
  undolikeComment,
  clearNewPostState,
  deletePost,
  votePostSuccess,
  setUserLocation,
} from './handlers'

const actionHandlers = {
  [LOADING_POSTS]: loadingPosts,
  [FETCH_POSTS]: fetchPosts,
  [REFRESH_POSTS]: refreshPosts,
  [LOADING_POST]: loadingPost,
  [PUBLISHING_POST]: publishingPost,
  [PUBLISH_POST_SUCCESS]: publishPost,
  [SAVE_OPEN_GRAPH]: saveOpenGraph,
  [SAVE_OG_URLS_FOUND]: saveOgUrlsFound,
  [SAVE_OG_URLS_DISMISSED]: saveOgUrlsDismissed,
  [LOADING_OG]: loadingOg,
  [SHOW_FEED_LOADING]: showFeedLoadingHandler,
  [HIDE_FEED_LOADING]: hideLoadingHandler,
  [UPDATE_POST_STATUS_ON_FEED]: updatePostStatusOnFeed,
  [DELETE_POST_SUCCESS]: deletePost,
  [LIKE_POST_SUCCESS]: likePost,
  [UNDO_LIKE_POST_SUCCESS]: undolikePost,
  [LOADING_COMMENTS]: loadingComments,
  [FETCH_COMMENTS]: fetchComments,
  [FETCH_MORE_COMMENTS]: fetchMoreComments,
  [PUBLISH_COMMENT_SUCCESS]: publishCommentSuccess,
  [EDIT_COMMENT_SUCCESS]: editCommentSuccess,
  [DELETE_COMMENT_SUCCESS]: deleteCommentSuccess,
  [CLEAR_COMMENTS]: clearComments,
  [SHARE_POST_SUCCESS]: sharePostSuccess,
  [LIKE_COMMENT_SUCCESS]: likeComment,
  [UNDO_LIKE_COMMENT_SUCCESS]: undolikeComment,
  [CLEAR_NEW_POST_STATE]: clearNewPostState,
  [VOTE_POST_SUCCESS]: votePostSuccess,
  [SET_USER_LOCATION]: setUserLocation,
}

export const feedReducerConfig = {
  initialState: FEED_INITIAL_STATE,
  actionHandlers
}
