export { MenuModal } from './menuModal'
export { ModalSelect } from './modalSelect'
export { ModalParagraphsFullScreen } from './modalParagraphsFullScreen'
export { VideoModal } from './videoModal'
export { ImagesGallery } from './imagesGallery'
